### ISSUE TITLE
Remove request_structure from widget endpoint

### ISSUE THREAD

**Issue by andersbjorkland** [northcreation-agency/NCASyliusKlarnaGatewayPlugin#15]
A GET request to _/api/v2/shop/orders/{{orderToken}}/klarna-widget_ will return a body on this format:
```json
{
  "snippet": "<div>...</div>",
  "request_structure": {}
}
```

It should be only:
```json
{
  "snippet": "<div>...</div>"
}
```

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign this issue to me.
